"""add lease_until to publish_records

Revision ID: 6b14e9d054c6
Revises: 0002_create_core_models
Create Date: 2026-05-08 11:45:38.070333
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '6b14e9d054c6'
down_revision: Union[str, None] = '0002_create_core_models'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publish_records', sa.Column('lease_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publish_records', 'lease_until')
    # ### end Alembic commands ###

